### ISSUE TITLE
Requesting to add the login button

### ISSUE THREAD

**Issue by COBRAKING007** [DineshVenkatesan/WhatsAppDevelepment#3]
Dear Dinesh,

your code is good but by adding login button it will get fulfilled.
so try to add new function
Thank you

**Comment by DineshVenkatesan** [comment]
Dear COBRA thanks for suggesting the feature
Will try to add it soon as possible.
Thank you

**Comment by DineshVenkatesan** [comment]
Dear COBRA,
As you suggestion, the login button was created.
Keep giving more suggestions.

**Comment by COBRAKING007** [comment]
Hello Dinesh,
Kindly add the create new account button in the login page
